//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRepairShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangesDataBase
    {
        public int Id_Change { get; set; }
        public string Changer_surnameAndname { get; set; }
        public string Change_date { get; set; }
        public string Change { get; set; }
    }
}
